name: build deps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cd deps
          for p in miniz sqlite; do rm $p/src/*; done

      - run: |
          cd $(mktemp -d)
          wget -qO- https://sqlite.org/src/tarball/sqlite.tar.gz?r=release | tar xz
          cd sqlite
          sh configure
          make sqlite3.c
          mv sqlite3.c sqlite3.h $GITHUB_WORKSPACE/deps/sqlite/src

      - run: |
          cd $(mktemp -d)
          gh release download --repo richgel999/miniz -p miniz-*.zip
          unzip *.zip
          mv miniz.c miniz.h $GITHUB_WORKSPACE/deps/miniz/src
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          ! git diff --quiet || exit 0
          git add -A
          git commit -m generated
          git push

  build:
    needs: fetch

    strategy:
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, windows-latest ] # FIXME : there's no ubuntu-latest-arm
        dep: [ microhttpd, sqlite, miniz, curl-impersonate ]
        exclude:
          - os: windows-latest
            dep: curl-impersonate

    runs-on: ${{ matrix.os }}
    container: ${{ startsWith(matrix.os, 'ubuntu') && 'alpine' || null }}

    steps:
      - uses: laverdet/alpine-arm64@v1
      - uses: actions/checkout@v4

      - run: choco install wget --no-progress -y
        if: ${{ matrix.os == 'windows-latest' }}

      # FIXME: github does not support matrix in job definition
      - run: ./${{ matrix.dep }}.sh
        working-directory: deps
        shell: bash
        if: ${{ matrix.os == 'windows-latest' }}

      - run: ./${{ matrix.dep }}.sh
        working-directory: deps
        if: ${{ matrix.os != 'windows-latest' }}

      - uses: actions/upload-artifact@v4
        with:
          name: lib-linux-${{ strategy.job-index }}
          path: deps/generated
          if-no-files-found: error

  build-windows-curl:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: ./curl-impersonate.sh
        shell: bash
        working-directory: deps
        env:
          GH_TOKEN: ${{ github.token }}

      - run: |
          cd curl-impersonate-*
          win\build.bat vcvars64
        shell: cmd

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - run: |
          cd curl-impersonate-*\packages

          del lib\zlib.lib
          del lib\libcurl-impersonate_imp.lib

          lib /OUT:curl.lib lib\*.lib
        shell: cmd

      - run: |
          cd curl-impersonate-*/packages

          DIR=$DST/include/curl
          mkdir -p $DIR

          mv include/curl/* $DIR
          mv curl.lib $DST_LIB
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          name: lib-windows-curl
          path: deps/generated
          if-no-files-found: error

  commit:
    runs-on: ubuntu-latest
    needs: [ build-windows-curl, build ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/download-artifact@v4
        with:
          path: artifact
          pattern: lib-*
          merge-multiple: true

      - run: |
          rm deps/microhttpd/include/*.h
          rm deps/curl-impersonate/include/curl/*.h

          rsync -av artifact/ deps/
          rm -rf artifact

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m generated
          git push
